// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimeChat.proto

package grpc.examples.realtimeChat;

public final class realtimeChatServiceImpl {
  private realtimeChatServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_ServerSideChat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_ServerSideChat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_ClientSideChat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_ClientSideChat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022realtimeChat.proto\022\007strings\"!\n\016ServerS" +
      "ideChat\022\017\n\007message\030\001 \001(\t\"!\n\016ClientSideCh" +
      "at\022\017\n\007message\030\001 \001(\t2N\n\004chat\022F\n\014realtimeC" +
      "hat\022\027.strings.ServerSideChat\032\027.strings.C" +
      "lientSideChat\"\000(\0010\001B7\n\032grpc.examples.rea" +
      "ltimeChatB\027realtimeChatServiceImplP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_strings_ServerSideChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_strings_ServerSideChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_ServerSideChat_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_strings_ClientSideChat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_strings_ClientSideChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_ClientSideChat_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
