// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimeChat.proto

package grpc.examples.realtimeChat;

public interface ServerSideChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.ServerSideChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
