// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimeChat.proto

package grpc.examples.realtimeChat;

public interface uploadSuccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.uploadSuccess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uploadConfirm = 1;</code>
   */
  java.lang.String getUploadConfirm();
  /**
   * <code>string uploadConfirm = 1;</code>
   */
  com.google.protobuf.ByteString
      getUploadConfirmBytes();
}
