// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: realtimeChat.proto

package grpc.examples.realtimeChat;

public interface uploadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.upload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uploadRequest = 1;</code>
   */
  java.lang.String getUploadRequest();
  /**
   * <code>string uploadRequest = 1;</code>
   */
  com.google.protobuf.ByteString
      getUploadRequestBytes();
}
