// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package grpc.example.helloworld;

public final class DemoHelloWorldServiceImpl {
  private DemoHelloWorldServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extrahelloworld_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extrahelloworld_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_extrahelloworld_LoginReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_extrahelloworld_LoginReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020HelloWorld.proto\022\017extrahelloworld\"(\n\014L" +
      "oginRequest\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"\035\n" +
      "\nLoginReply\022\017\n\007message\030\001 \001(\t2R\n\005LogIn\022I\n" +
      "\tInputInfo\022\035.extrahelloworld.LoginReques" +
      "t\032\033.extrahelloworld.LoginReply\"\000B6\n\027grpc" +
      ".example.helloworldB\031DemoHelloWorldServi" +
      "ceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_extrahelloworld_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_extrahelloworld_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extrahelloworld_LoginRequest_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_extrahelloworld_LoginReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_extrahelloworld_LoginReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_extrahelloworld_LoginReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
