// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package grpc.example.helloworld;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:extrahelloworld.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
