// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employeeRegistration.proto

package grpc.examples.employeeRegistration;

/**
 * Protobuf type {@code strings.employee}
 */
public  final class employee extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:strings.employee)
    employeeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use employee.newBuilder() to construct.
  private employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private employee() {
    empNo_ = 0;
    empName_ = "";
    shift_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private employee(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            empNo_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            empName_ = s;
            break;
          }
          case 24: {

            shift_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.examples.employeeRegistration.EmployeeRegistrationServiceImpl.internal_static_strings_employee_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.examples.employeeRegistration.EmployeeRegistrationServiceImpl.internal_static_strings_employee_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.examples.employeeRegistration.employee.class, grpc.examples.employeeRegistration.employee.Builder.class);
  }

  public static final int EMPNO_FIELD_NUMBER = 1;
  private int empNo_;
  /**
   * <code>int32 empNo = 1;</code>
   */
  public int getEmpNo() {
    return empNo_;
  }

  public static final int EMPNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object empName_;
  /**
   * <code>string empName = 2;</code>
   */
  public java.lang.String getEmpName() {
    java.lang.Object ref = empName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      empName_ = s;
      return s;
    }
  }
  /**
   * <code>string empName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEmpNameBytes() {
    java.lang.Object ref = empName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      empName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHIFT_FIELD_NUMBER = 3;
  private int shift_;
  /**
   * <code>int32 shift = 3;</code>
   */
  public int getShift() {
    return shift_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (empNo_ != 0) {
      output.writeInt32(1, empNo_);
    }
    if (!getEmpNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, empName_);
    }
    if (shift_ != 0) {
      output.writeInt32(3, shift_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (empNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, empNo_);
    }
    if (!getEmpNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, empName_);
    }
    if (shift_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, shift_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.examples.employeeRegistration.employee)) {
      return super.equals(obj);
    }
    grpc.examples.employeeRegistration.employee other = (grpc.examples.employeeRegistration.employee) obj;

    boolean result = true;
    result = result && (getEmpNo()
        == other.getEmpNo());
    result = result && getEmpName()
        .equals(other.getEmpName());
    result = result && (getShift()
        == other.getShift());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMPNO_FIELD_NUMBER;
    hash = (53 * hash) + getEmpNo();
    hash = (37 * hash) + EMPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getEmpName().hashCode();
    hash = (37 * hash) + SHIFT_FIELD_NUMBER;
    hash = (53 * hash) + getShift();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.examples.employeeRegistration.employee parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.examples.employeeRegistration.employee parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.examples.employeeRegistration.employee parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.examples.employeeRegistration.employee parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.examples.employeeRegistration.employee parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.examples.employeeRegistration.employee parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.examples.employeeRegistration.employee parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.examples.employeeRegistration.employee parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.examples.employeeRegistration.employee parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.examples.employeeRegistration.employee parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.examples.employeeRegistration.employee parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.examples.employeeRegistration.employee parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.examples.employeeRegistration.employee prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code strings.employee}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:strings.employee)
      grpc.examples.employeeRegistration.employeeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.examples.employeeRegistration.EmployeeRegistrationServiceImpl.internal_static_strings_employee_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.examples.employeeRegistration.EmployeeRegistrationServiceImpl.internal_static_strings_employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.examples.employeeRegistration.employee.class, grpc.examples.employeeRegistration.employee.Builder.class);
    }

    // Construct using grpc.examples.employeeRegistration.employee.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      empNo_ = 0;

      empName_ = "";

      shift_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.examples.employeeRegistration.EmployeeRegistrationServiceImpl.internal_static_strings_employee_descriptor;
    }

    @java.lang.Override
    public grpc.examples.employeeRegistration.employee getDefaultInstanceForType() {
      return grpc.examples.employeeRegistration.employee.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.examples.employeeRegistration.employee build() {
      grpc.examples.employeeRegistration.employee result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.examples.employeeRegistration.employee buildPartial() {
      grpc.examples.employeeRegistration.employee result = new grpc.examples.employeeRegistration.employee(this);
      result.empNo_ = empNo_;
      result.empName_ = empName_;
      result.shift_ = shift_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.examples.employeeRegistration.employee) {
        return mergeFrom((grpc.examples.employeeRegistration.employee)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.examples.employeeRegistration.employee other) {
      if (other == grpc.examples.employeeRegistration.employee.getDefaultInstance()) return this;
      if (other.getEmpNo() != 0) {
        setEmpNo(other.getEmpNo());
      }
      if (!other.getEmpName().isEmpty()) {
        empName_ = other.empName_;
        onChanged();
      }
      if (other.getShift() != 0) {
        setShift(other.getShift());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.examples.employeeRegistration.employee parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.examples.employeeRegistration.employee) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int empNo_ ;
    /**
     * <code>int32 empNo = 1;</code>
     */
    public int getEmpNo() {
      return empNo_;
    }
    /**
     * <code>int32 empNo = 1;</code>
     */
    public Builder setEmpNo(int value) {
      
      empNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 empNo = 1;</code>
     */
    public Builder clearEmpNo() {
      
      empNo_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object empName_ = "";
    /**
     * <code>string empName = 2;</code>
     */
    public java.lang.String getEmpName() {
      java.lang.Object ref = empName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        empName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string empName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmpNameBytes() {
      java.lang.Object ref = empName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        empName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string empName = 2;</code>
     */
    public Builder setEmpName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      empName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string empName = 2;</code>
     */
    public Builder clearEmpName() {
      
      empName_ = getDefaultInstance().getEmpName();
      onChanged();
      return this;
    }
    /**
     * <code>string empName = 2;</code>
     */
    public Builder setEmpNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      empName_ = value;
      onChanged();
      return this;
    }

    private int shift_ ;
    /**
     * <code>int32 shift = 3;</code>
     */
    public int getShift() {
      return shift_;
    }
    /**
     * <code>int32 shift = 3;</code>
     */
    public Builder setShift(int value) {
      
      shift_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 shift = 3;</code>
     */
    public Builder clearShift() {
      
      shift_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:strings.employee)
  }

  // @@protoc_insertion_point(class_scope:strings.employee)
  private static final grpc.examples.employeeRegistration.employee DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.examples.employeeRegistration.employee();
  }

  public static grpc.examples.employeeRegistration.employee getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<employee>
      PARSER = new com.google.protobuf.AbstractParser<employee>() {
    @java.lang.Override
    public employee parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new employee(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<employee> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<employee> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.examples.employeeRegistration.employee getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

