// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employeeRegistration.proto

package grpc.examples.employeeRegistration;

public interface emptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.empty)
    com.google.protobuf.MessageOrBuilder {
}
