// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employeeRegistration.proto

package grpc.examples.employeeRegistration;

public interface loginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.loginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 empNo = 1;</code>
   */
  int getEmpNo();

  /**
   * <code>string empName = 2;</code>
   */
  java.lang.String getEmpName();
  /**
   * <code>string empName = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmpNameBytes();
}
