// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employeeRegistration.proto

package grpc.examples.employeeRegistration;

public interface logoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.logoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmMessage = 1;</code>
   */
  java.lang.String getConfirmMessage();
  /**
   * <code>string confirmMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmMessageBytes();

  /**
   * <code>.strings.logoutResponse.Enum detail = 2;</code>
   */
  int getDetailValue();
  /**
   * <code>.strings.logoutResponse.Enum detail = 2;</code>
   */
  grpc.examples.employeeRegistration.logoutResponse.Enum getDetail();
}
