// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: securityDeviceCheck.proto

package grpc.examples.securityDeviceCheck;

public interface emptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.empty)
    com.google.protobuf.MessageOrBuilder {
}
