// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: securityDeviceCheck.proto

package grpc.examples.securityDeviceCheck;

public interface loginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.loginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>string confirm = 2;</code>
   */
  java.lang.String getConfirm();
  /**
   * <code>string confirm = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfirmBytes();
}
