// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: securityDeviceCheck.proto

package grpc.examples.securityDeviceCheck;

public interface logoutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.logoutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmMessage = 1;</code>
   */
  java.lang.String getConfirmMessage();
  /**
   * <code>string confirmMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmMessageBytes();
}
