// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: securityDeviceCheck.proto

package grpc.examples.securityDeviceCheck;

public final class SecurityDeviceCheckServiceImpl {
  private SecurityDeviceCheckServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_deviceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_deviceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_deviceList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_deviceList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031securityDeviceCheck.proto\022\007strings\"!\n\r" +
      "deviceRequest\022\020\n\010massData\030\001 \001(\t\"\031\n\ndevic" +
      "eList\022\013\n\003val\030\001 \001(\t2D\n\004user\022<\n\013deviceChec" +
      "k\022\026.strings.deviceRequest\032\023.strings.devi" +
      "ceList0\001BE\n!grpc.examples.securityDevice" +
      "CheckB\036SecurityDeviceCheckServiceImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_strings_deviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_strings_deviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_deviceRequest_descriptor,
        new java.lang.String[] { "MassData", });
    internal_static_strings_deviceList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_strings_deviceList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_deviceList_descriptor,
        new java.lang.String[] { "Val", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
